Enhance find command
AY2122S1-CS2103T-T11-2/tp pull request #104
Opened 2021-10-16 06:21 UTC by sharmainec

### Description

Find command accepts foreign keywords

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements

### How to test

1. Manually test by using the find command (e.g. 'FIND 早')
2. If keyword contains 1 character, will output flashcards containing that keyword
3. If keyword contains more than 1 character, will output flashcards containing the entire keyword _(needs to be a full match)_

### Checklist

- [x] I have written testcases to cover all new methods
- [x] I have built and manually tested this code
- [ ] I have updated the User Guide
- [ ] I have updated the Developer Guide
- [ ] I have updated my individual project portfolio
- [ ] I have included a preview deployment link to the updated project documentation

closes #101

2021-10-16 09:16 UTC, aikenwx requested changes
Also don't forget to updated user guide documentation for the updated find command

2021-10-16 09:16 UTC, aikenwx commented on src/main/java/lingogo/commons/util/StringUtil.java
> +
Change this whole segment to `sentence.contains(word)`

2021-10-16 09:16 UTC, aikenwx commented on src/main/java/lingogo/logic/commands/FindCommand.java
>              + "Example: " + COMMAND_WORD + " hello";
Allow user to specify find by prefix e/ for EnglishPhrase, f/ for ForeignPhrase

2021-10-17 17:09 UTC, kwokieee requested changes
Thanks for making the modifications! In addition to the comments, perhaps for the tests in `FindCommandTest`, `FindCommandParserTest`, and `FlashcardAppParserTest`, we could also add the case where the user uses the `Find` command with both English and Foreign phrase prefix?

2021-10-18 14:08 UTC, merged