Edited Import and Export commands
AY2122S1-CS2103T-T11-2/tp pull request #191
Opened 2021-10-30 10:16 UTC by jhlee1997

### Description

Fixes made in response to PED errors
- TBD

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Code quality improvements

### How to test

1. Check the UG
2. TBD

### Checklist

- [X] I have written testcases to cover all new methods
- [X] I have built and manually tested this code
- [X] I have updated the User Guide
- [X] I have updated the Developer Guide
- [ ] I have updated my individual project portfolio
- [ ] I have included a preview deployment link to the updated project documentation

2021-10-30 13:44 UTC, chownces commented
Reviewer to check if the new implementation handles duplicated flashcards in CSV, and also CSV entries that already exist in the app.

Also, `import` should not use `.contains` to check if a particular flashcard already exists (as this uses the `equals` method) --> should use the `isSameFlashcard` method instead

2021-10-31 10:00 UTC, sharmainec requested changes
Minor changes are required for some error messages

2021-11-02 17:43 UTC, kwokieee requested changes
`LogicManager`
- Change the implementation of `execute`'s try-catch block to not throw a new `CommandException` with the `IOException` in the message

For `ImportCommandTest` and `ExportCommandTest`, try and create the `expectedModel` within each test and manually create an instance of the `expectedModel` (can refer to other tests)

2021-11-02 17:43 UTC, kwokieee commented on src/test/java/lingogo/logic/commands/ExportCommandTest.java
>          assertCommandSuccess(command, model, expectedMessage, expectedModel);
I think can just use `model` as the `expectedModel`, since exporting shouldn't change the `model` at all right?

2021-11-02 17:43 UTC, kwokieee commented on src/test/java/lingogo/logic/commands/ImportCommandTest.java
> +            command.importHelper(expectedModel);
We shouldn't need to do anything to `expectedModel` since it already has all the flashcards we expect right?

2021-11-02 17:43 UTC, kwokieee commented on src/test/java/lingogo/logic/parser/ImportCommandParserTest.java
>      public void parse_nonExistentFile_throwsParseException() {
Should be handled by `ImportCommand` instead of its parser (see above)

2021-11-03 18:09 UTC, kwokieee requested changes
In addition to the few comments, could you also make the change for `LogicManager::execute` mentioned in my previous PR review?

2021-11-04 04:40 UTC, kwokieee approved these changes

2021-11-04 07:48 UTC, merged