Add tests for list
AY2122S1-CS2103T-T11-2/tp pull request #195
Opened 2021-10-30 16:45 UTC by kwokieee

### Description

- Created tests for listing a random number of flashcards.
- Added equals test for `ListCommand`.
- Fixed some errors spotted in Javadocs for `FlashcardInGivenFlashcardListPredicate`.

Closes #147.

### Type of change

- [x] Adding tests

### How to test

### Checklist

- [x] I have written testcases to cover all new methods
- [x] I have built and manually tested this code
- [ ] I have updated the User Guide
- [ ] I have updated the Developer Guide
- [ ] I have updated my individual project portfolio
- [ ] I have included a preview deployment link to the updated project documentation

2021-10-31 12:03 UTC, jhlee1997 approved these changes
LGTM

2021-11-03 06:11 UTC, chownces requested changes

2021-11-03 06:11 UTC, chownces commented on src/test/java/lingogo/logic/commands/ListCommandTest.java
> +    }
Missing method body?

2021-11-03 06:11 UTC, chownces commented on src/main/java/lingogo/model/flashcard/FlashcardInGivenFlashcardListPredicate.java
> +    }
We can just use the constructor above? (just create a `new List(phrase1, phrase2, ...)` inside the test)

2021-11-03 06:11 UTC, chownces commented on src/test/java/lingogo/logic/commands/ListCommandTest.java
>      }
would be nice to add another positive test case with a different seed too!

2021-11-04 07:30 UTC, chownces approved these changes
LGTM. Thanks!

2021-11-04 07:37 UTC, merged