Add UG documentation of flip and test commands
AY2122S1-CS2103T-T11-2/tp pull request #36
Opened 2021-09-26 15:37 UTC by aikenwx

closes #13

2021-09-27 02:46 UTC, chownces requested changes

2021-09-27 02:46 UTC, chownces commented on docs/UserGuide.md
> +5. Type the command in the command box and press Enter to execute it. e.g. typing **`help`** and pressing Enter will open the help window.<br>
We can stick to using all 1s. Markdown automatically handles the numbering for us. This allows us to perform minimal changes if updates are needed in the future

2021-09-27 02:46 UTC, chownces commented on docs/UserGuide.md
> +6. Refer to the [Features](#features) below for details of each command.
see comment above

2021-09-27 02:46 UTC, chownces commented on docs/UserGuide.md
> +* Similar to delete, the index **must be a positive integer** 1, 2, 3, …​
Can we follow the format of the rest of the documentation? For example

```
### Deleting a person : `delete`
Deletes the specified person from the address book.
Format: `delete INDEX`
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index **must be a positive integer** 1, 2, 3, …​
```

I have deployed this commit `6de3fa1` here for reference: https://a8d12ad0.tp-b32.pages.dev/

2021-09-27 02:46 UTC, chownces commented on docs/UserGuide.md
> +Format: `test INDEX WORD`
see comment above on format

2021-09-27 03:08 UTC, chownces commented
Command summary at the bottom of UserGuide needs to be updated too

2021-09-28 17:44 UTC, kwokieee requested changes

2021-09-28 17:44 UTC, kwokieee commented on docs/UserGuide.md
> +Format: `test INDEX WORD`
```suggestion
Format: `test INDEX ENGLISH_PHRASE`
```

Let's standardize across all commands and use `ENGLISH_PHRASE` for now

2021-09-29 07:52 UTC, kwokieee approved these changes

2021-09-29 15:22 UTC, chownces approved these changes

2021-09-29 16:13 UTC, merged